### ISSUE TITLE
AMI not found error

### ISSUE THREAD

**Issue by mikkin** [adphillips/ec2-slave-plugin#2]
I get the AMI not found error when checking for AMI's. Any clue? Using Jenkins version 1.442

Status Code: 400, AWS Request ID: 8b4d0953-3e43-47f1-a696-aff108f9ea91, AWS Error Code: InvalidAMIID.NotFound, AWS Error Message: The AMI ID 'ami-012b7a44' does not exist
    at com.amazonaws.http.HttpClient.handleErrorResponse(HttpClient.java:586)
    at com.amazonaws.http.HttpClient.execute(HttpClient.java:282)
    at com.amazonaws.http.HttpClient.execute(HttpClient.java:160)
    at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:5010)
    at com.amazonaws.services.ec2.AmazonEC2Client.describeImages(AmazonEC2Client.java:2367)
    at jenkins.plugins.ec2slave.EC2ImageSlave$DescriptorImpl.doValidateAmi(EC2ImageSlave.java:158)

I am going to look at the source code tomorrow, but just thought I drop in this here in case if anyone knows about it.
(BTW - The AMI id specified in the stack trace is a public image. So feel free to use the same ID)

Thanks!
Mikkin

**Comment by mikkin** [comment]
The problem is that the code does not provide a region to search for AMIs. Also, the region box in the UI does not get used for this particular AMI. In short, you should have something like this to your ec2 object:

ec2.setEndPoint(regionName) #Also note that specifying us-west-1a does not work. I had to specify us-west-1.ec2.amazonaws.com for it to work. This needs to be exposed to the interface though.
